FROM qtrace:build AS build

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y gdb python-is-python3 python3-dev python3-pip

RUN pip install pytest

COPY --from=build /opt/qtrace/dist /tmp
RUN pip install /tmp/qtrace-*.whl

ADD tests /tests

CMD pytest -v --pdb /tests
