name: Publish to PyPi
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
    - uses: docker/setup-buildx-action@master
    - name: Cache Docker Layers
      uses: actions/cache@master
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker Build
      uses: docker/build-push-action@master
      with:
        tags: qtrace:latest
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
    - name: Run Tests
      run: |
        docker run -t --rm qtrace:latest
    - name: Build Wheel
      run: |
        docker run --rm -v $PWD/dist:/dist qtrace:latest
    - uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
